---
run:
  deadline: 10m
issues:
  exclude-rules:
    # counterfeiter fakes are usually named 'fake_<something>.go'
    - path: fake_.*\.go
      linters:
        - gocritic
        - golint
        - dupl
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - logrlint
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    # - cyclop
    # - exhaustive
    # - exhaustruct
    # - exportloopref
    # - forbidigo
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - godot
    # - goerr113
    # - gomnd
    # - gosec
    # - ireturn
    # - lll
    # - nestif
    # - nlreturn
    # - noctx
    # - nolintlint
    # - paralleltest
    # - tagliatelle
    # - testpackage
    # - varnamelen
    # - wrapcheck
    # - wsl
linters-settings:
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-checks:
      # Diagnostic
      - badLock
      - badRegexp
      - badSorting
      - builtinShadowDecl
      - commentedOutCode
      - deferInLoop
      - dynamicFmtString
      - emptyDecl
      - evalOrder
      - externalErrorReassign
      - filepathJoin
      - nilValReturn
      - regexpPattern
      - returnAfterHttpError
      - sloppyReassign
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - syncMapLoadAndDelete
      - truncateCmp
      - unnecessaryDefer
      - weakCond

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - preferDecodeRune
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - rangeExprCopy
      - rangeValCopy
      - sliceClear
      - stringXbytes

      # Style
      - boolExprSimplify
      - commentedOutImport
      - deferUnlambda
      - docStub
      - dupImport
      - emptyFallthrough
      - emptyStringTest
      - exposedSyncMutex
      - hexLiteral
      - httpNoBody
      - methodExprCall
      - octalLiteral
      - preferFilepathJoin
      - redundantSprint
      - regexpSimplify
      - ruleguard
      - stringConcatSimplify
      - stringsCompare
      - timeExprSimplify
      - tooManyResultsChecker
      - typeAssertChain
      - typeDefFirst
      - unlabelStmt
      - yodaStyleExpr
      # - whyNoLint

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock
