---
run:
  timeout: 10m
issues:
  exclude-rules:
    # counterfeiter fakes are usually named 'fake_<something>.go'
    - path: fake_.*\.go
      linters:
        - gocritic
        - golint
        - dupl
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - fatcontext
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
    # - cyclop
    # - depguard
    # - err113
    # - exhaustive
    # - exhaustruct
    # - forbidigo
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gosec
    # - inamedparam
    # - ireturn
    # - lll
    # - mnd
    # - musttag
    # - nlreturn
    # - noctx
    # - paralleltest
    # - tagliatelle
    # - testpackage
    # - varnamelen
    # - wrapcheck
    # - wsl
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(k8s.io)
      - prefix(sigs.k8s.io)
      - localmodule
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-checks:
      - appendCombine
      - badLock
      - badRegexp
      - badSorting
      - badSyncOnceFunc
      - boolExprSimplify
      - builtinShadow
      - builtinShadowDecl
      - commentedOutCode
      - commentedOutImport
      - deferInLoop
      - deferUnlambda
      - docStub
      - dupImport
      - dynamicFmtString
      - emptyDecl
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exposedSyncMutex
      - externalErrorReassign
      - filepathJoin
      - hexLiteral
      - httpNoBody
      - hugeParam
      - importShadow
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - nilValReturn
      - octalLiteral
      - paramTypeCombine
      - preferDecodeRune
      - preferFilepathJoin
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - redundantSprint
      - regexpPattern
      - regexpSimplify
      - returnAfterHttpError
      - ruleguard
      - sliceClear
      - sloppyReassign
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - stringConcatSimplify
      - stringXbytes
      - stringsCompare
      - syncMapLoadAndDelete
      - timeExprSimplify
      - todoCommentWithoutDetail
      - tooManyResultsChecker
      - truncateCmp
      - typeAssertChain
      - typeDefFirst
      - typeUnparen
      - uncheckedInlineErr
      - unlabelStmt
      - unnamedResult
      - unnecessaryBlock
      - unnecessaryDefer
      - weakCond
      - yodaStyleExpr
      # - whyNoLint
