---
defaultBaseImage: cgr.dev/chainguard/static:latest

builds:
  - id: zeitgeist
    dir: ./remote/zeitgeist
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"

  - id: buoy
    dir: ./buoy
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"
