---
defaultBaseImage: gcr.io/distroless/static-debian12

builds:
  - id: zeitgeist
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"

  - id: buoy
    dir: ./buoy
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"
