version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS
    - restore_cache:
        keys:
        - pkg-cache-{{ checksum "go.sum" }}
        - pkg-cache-
    - run:
        name: Linting
        command: make lint
    - run:
        name: Build executable
        command: make build
    - run:
        name: Run unit tests
        command: |
          make test | tee ${TEST_RESULTS}/go-test.out
          cp coverage.out ${TEST_RESULTS}/coverage.out
    - save_cache:
        key: pkg-cache-{{ checksum "go.sum" }}
        paths:
        - "/go/pkg"
    - store_artifacts:
        path: ${TEST_RESULTS}
        destination: raw-test-output
    - store_test_results:
        path: ${TEST_RESULTS}

  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Import GPG key
          command: echo -e "$GPG_KEY" | gpg --import
      - run:
          name: Release with GoReleaser
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
    - build
  release:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
