version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run:
        name: Linting
        command: make lint
    - run:
        name: Build executable
        command: make build
    - run:
        name: Run unit tests
        command: |
          make test | tee ${TEST_RESULTS}/go-test.out
          cp coverage.out ${TEST_RESULTS}/coverage.out
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results
