name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    env:
      GOPATH: ${{ github.workspace }}
      COSIGN_YES: "true"

    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}

    - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.3.0
      with:
        go-version: 1.20
        check-latest: true

    - name: Install ko
      uses: ko-build/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.6

    - name: Install cosign
      uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # v3.0.1

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
      with:
        install-only: true

    - name: Get TAG
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

    - name: Run goreleaser
      working-directory: ./src/github.com/${{ github.repository }}
      run: make goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
